name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test1:
    name: Test1
    runs-on: ubuntu-22.04
    steps:
      - name: test-step
        run: |
          curl --version
          curl -ks https://www.google.com -o /dev/null -w '{"status": %{http_code}, "headers": %{json}}' | jq
