name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test1:
    name: Test1
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v2.1.8
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: src/assets/images
          # An explicit key for restoring and saving the cache
          key: ci-build-${{ hashFiles('.github/workflows/test.yml', 'abc', 'README.md') }}
